### ISSUE TITLE
Unable to get vs code working.

### ISSUE THREAD

**Issue by justadamhopkins** [stefanstranger/vscode-microsoftteams#4]
Hi 

I have installed the plugin and setup the necessary webhook. However, i am unable to understand how you send messages or files. I can't see any extension for teams inside my vscode.

Could you please explain this to me or add it to read me.

**Comment by Dragod** [comment]
> Hi
> 
> I have installed the plugin and setup the necessary webhook. However, i am unable to understand how you send messages or files. I can't see any extension for teams inside my vscode.
> 
> Could you please explain this to me or add it to read me.

Same here, I did add the webhook but I have no idea on how to send messages, any help is appreciated.

**Comment by Dragod** [comment]
ok figured it out: ctrl+shift+p then type Microsoft
